modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/CreativeMD/ItemPhysic/issues"
logoFile="itemphysic.png"
license="GNU General Public License v3.0"

[[mods]]
	modId="itemphysic"
	version="${file.jarVersion}"
	displayName="ItemPhysic"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/itemphysic"
	authors=["CreativeMD"]
	description='''Enhances the rendering of items and introduces some more physics'''
	
[[dependencies.itemphysic]]
	modId="creativecore"
	mandatory=true
	ordering="NONE"
	side="BOTH"
	versionRange="[2.4.0,)"